# Generated by Django 3.2.12 on 2022-04-09 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='additionaldata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_activities', models.CharField(max_length=50)),
                ('training_style', models.CharField(max_length=50)),
                ('proposed_objectives', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='personaldata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('preexisting_condition', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='studentsdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('adress', models.CharField(max_length=50)),
            ],
        ),
    ]
