# Generated by Django 3.2.12 on 2022-04-11 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentsdata',
            old_name='adress',
            new_name='address',
        ),
    ]
